'use strict';
const redis = require('../db/redisClient');
const cashfree = require('../config/cashfree');
const crypto = require('crypto');
const { validateRegistrationBody } = require('../config/validation');
const { orderIdExists, getOrderData,printOrderMap, addOrderIdtoCache } = require('../services/orderIdService');
const { eventIdExists, addEventIdtoCache } = require('../services/webhookEventId');
const { broadcast } = require('./countController');

// ─── POST /api/hackathon/initiate ───────────
// Body: { teamName, participants: [{ name, email, phone, college, isLeader }] }
// Response: { orderId, paymentSessionId, amount, currency }

async function initiatePayment(req, res) {
  const count = Number(await redis.get('team_counter'));
  try {
    if (count >= parseInt(process.env.MAX_SEATS)) {
      return res.status(403).json({ error: "Registration are Closed Now" });
    }
    console.log("/initiate route fired");
    console.log(` before validation `,req.body);
    const validationError = validateRegistrationBody(req.body);
    if (validationError) {
      console.warn("not able to validate", validationError);
      return res.status(400).json({ error: validationError });
    }

    const { teamName, participants } = req.body;

    const leader = participants.find(p => p.isLeader);
    const leaderEmail = leader.email.trim().toLowerCase();
    const leaderPhone = leader.phone.trim();

    // Calculate amount
    let amountPaise = parseInt(process.env.REGISTRATION_FEE_PAISE, 10);
    const safeLocal = leaderEmail.split('@')[0].replace(/[^a-z0-9]/gi, '').slice(0, 10);

    // Cashfree requires a unique order_id generated by us (not by the gateway)
    const cfOrderId = `dlh_${Date.now()}_${safeLocal}`;

    if (req.body.promoCode) {
      const result = await resolvePromoCode(req.body.promoCode, amountPaise);
      if (result.valid) {
        amountPaise = result.finalAmountPaise;
        console.log(`[Hackathon] Promo "${req.body.promoCode.trim().toUpperCase()}" applied — ₹${(result.discountPaise / 100).toFixed(2)} off → ₹${(amountPaise / 100).toFixed(2)}`);
      } else {
        console.warn(`[Hackathon] Unknown promo code submitted: "${req.body.promoCode}" — ignoring.`);
      }
    }

    // Cashfree expects amount in Rupees (decimal), NOT paise
    const amountRupees = amountPaise / 100;

    // Create Cashfree Order
    const orderRequest = {
      order_id:       cfOrderId,
      order_amount:   amountRupees,
      order_currency: 'INR',
      customer_details: {
        customer_id:    leaderEmail.replace(/[^a-z0-9_]/gi, '_').slice(0, 50),
        customer_phone: leaderPhone,
        customer_email: leaderEmail,
        customer_name:  leader.name.trim(),
      },
      order_meta: {
        // Cashfree redirects here after the payment if the user leaves the modal (3DS, UPI redirect, etc.)
        return_url: `${process.env.FRONTEND_URL}/payment-success?order_id={order_id}`,
      },
      order_note: teamName,
    };

    const cfResponse = await cashfree.PGCreateOrder(orderRequest);
    const order = cfResponse.data;

    console.log(`order request` , order);
    const orderId = order.order_id ;
    // Store pending registration in Redis (TTL: 1 hour)
    const redisKey = `pending_registration:${order.order_id}`;
    const payload = {
      teamName: teamName.trim(),
      amount: amountPaise,                       // store in paise for consistent comparison
      participants: participants.map(p => ({
        name:     p.name.trim(),
        email:    p.email.trim().toLowerCase(),
        phone:    p.phone.trim(),
        college:  p.college.trim(),
        isLeader: p.isLeader,
      })),
    };

    console.log(payload);
    try{
      await redis.setex(redisKey, 3600, JSON.stringify(payload));

      const temp = await redis.get(orderId);

      console.log('redis pndRg',temp);
    }catch(err){
      console.log("redis issue",err);
    }
    console.log(`[Hackathon] Pending registration stored for Cashfree order ${order.order_id} | team: ${teamName}`);

    res.status(201).json({
      orderId:          order.order_id,
      paymentSessionId: order.payment_session_id, // Required by Cashfree JS SDK on frontend
      amount:           amountPaise,               // Keep paise for frontend consistency
      currency:         order.order_currency,
    });

  } catch (err) {
    console.error('[Hackathon] initiatePayment error:', err.response?.data || err);
    res.status(500).json({ error: 'Failed to create payment order. Please try again.' });
  }
}


// ─── POST /api/hackathon/webhook ──────────────────────────────────────────────
// IMPORTANT: This handler receives the RAW request body (Buffer), not parsed
// JSON. The route MUST be mounted with express.raw() before express.json().
//
// Signature verification:
//   HMAC-SHA256( timestamp + rawBody, CASHFREE_SECRET_KEY ) == x-webhook-signature
// Cashfree sends:
//   x-webhook-signature  — base64-encoded HMAC-SHA256
//   x-webhook-timestamp  — Unix timestamp of the event

async function handleWebhook(req, res) {
  console.log("/webhook route fired");

  const rawBody        = req.body;            // Buffer — because of express.raw()
  const rawBodyStr     = rawBody.toString('utf-8');
  const signature      = req.headers['x-webhook-signature'];
  const timestamp      = req.headers['x-webhook-timestamp'];

  if (!signature || !timestamp) {
    console.warn('[Webhook] Missing x-webhook-signature or x-webhook-timestamp header');
    return res.status(401).json({ error: 'Missing signature headers.' });
  }

  // ─── Signature Verification ───────────────────────────────────────────────
  // Cashfree: HMAC-SHA256(timestamp + rawBody, secretKey) → base64
  let isValid = false;
  try {
    const signStr = timestamp + rawBodyStr;
    const generatedSig = crypto
      .createHmac('sha256', process.env.CASHFREE_SECRET_KEY)
      .update(signStr)
      .digest('base64');
    isValid = generatedSig === signature;
  } catch (err) {
    console.error('[Webhook] Signature computation error:', err);
  }

  if (!isValid) {
    console.warn('[Webhook] Signature verification failed!');
    return res.status(401).json({ error: 'Invalid signature' });
  }

  let event;
  try {
    event = JSON.parse(rawBodyStr);
  } catch {
    return res.status(400).json({ error: 'Malformed JSON body.' });
  }

  const eventType = event.type;    // "PAYMENT_SUCCESS_WEBHOOK"
  console.log(`[Webhook] Verified Cashfree event: ${eventType}`);

  if (eventType !== 'PAYMENT_SUCCESS_WEBHOOK') {
    console.log(`[Webhook] Ignoring event: ${eventType}`);
    return res.status(200).json({ status: 'ok' });
  }

  console.log(event);

  // ─── Extract payment details ───────────────────────────────────────────────
  const orderDetails   = event?.data?.order;
  const paymentDetails = event?.data?.payment;

  if (!orderDetails || !paymentDetails) {
    console.error('[Webhook] Missing order or payment object in payload:', JSON.stringify(event));
    return res.status(200).json({ status: 'ok', note: 'missing_payment' });
  }

  const orderId       = orderDetails.order_id;
  const paymentId     = String(paymentDetails.cf_payment_id);  // Cashfree's unique payment ID
  const amountRupees  = paymentDetails.payment_amount;
  const amountPaise   = Math.round(amountRupees * 100);

  if (!orderId || !paymentId) {
    console.error('[Webhook] Invalid or missing order_id / cf_payment_id');
    return res.status(200).json({ status: 'ok', note: 'invalid_ids' });
  }

  // Idempotency: skip if this cf_payment_id was already processed
  if (eventIdExists(paymentId)) {
    console.log(`[Webhook] Duplicate cf_payment_id ${paymentId} — skipping.`);
    return res.status(200).json({ status: 'ok', note: 'duplicate' });
  }

  if (orderIdExists(orderId)) {
    return res.status(200).json({ status: 'ok', note: 'orderId exists' });
  }

  console.log(`[Webhook] Payment captured — orderId: ${orderId} | cf_payment_id: ${paymentId} | amount: ₹${amountRupees}`);

  // ─── Fetch pending registration from Redis ─────────────────────────────────
  const redisKey = `pending_registration:${orderId}`;
  let pending;
  try {
    pending = await redis.get(redisKey);
  } catch (err) {
    console.error('[Webhook] Failed to fetch pending registration:', err);
    return res.status(500).json({ error: 'Internal error fetching registration.' });
  }

  if (!pending) {
    console.error(`[Webhook] No pending registration found for orderId: ${orderId}`);
    return res.status(200).json({ status: 'ok', note: 'no_pending_registration' });
  }

  let payload;
  try {
    payload = JSON.parse(pending);
  } catch (parseErr) {
    console.error('[Webhook] Failed to parse pending registration JSON:', parseErr);
    return res.status(200).json({ error: 'Corrupt pending registration data.' });
  }

  // ─── Amount validation ─────────────────────────────────────────────────────
  if (payload.amount !== amountPaise) {
    console.error(`[Webhook] Amount mismatch! Stored: ${payload.amount}, Paid: ${amountPaise}`);
    return res.status(200).json({ status: 'ok', note: 'amount_mismatch' });
  }

  // ─── Assign team ID ────────────────────────────────────────────────────────
  let teamNumber;
  try {
    teamNumber = await redis.incr('team_counter');
  } catch (err) {
    return res.status(500).json({ error: 'redis error' });
  }
  const teamId = `DLH-${String(teamNumber).padStart(2, '0')}`;

  payload.teamId            = teamId.trim();
  payload.cashfreeOrderId   = orderId.trim();
  payload.cashfreePaymentId = paymentId.trim();
  payload.amountPaid        = amountPaise;
  payload.status            = 'registered';
  payload.createdAt         = new Date();

  const webhookEvent = {
    cashfreePaymentId: paymentId,
    event:             eventType,
  };

  console.log(orderId.trim());
  const queue = {
    payload,
    webhook_event: webhookEvent,
  };

  try {
    broadcast();
    await redis.lpush('registration_queue', JSON.stringify(queue));
    await redis.del(redisKey);
    // console.log(...payload);
    addOrderIdtoCache(payload);
    addEventIdtoCache(paymentId);
    res.status(200).json({ status: 'ok' });

    console.log(`[Webhook] Team "${payload.teamName}" (id: ${teamId}) registered successfully via webhook!`);

  } catch (err) {
    console.error(`[Webhook_Critical] Save failed to redis`, err);
    return res.status(500).json({ error: 'redis push failed retry' });
  }
}


// ─── GET /api/hackathon/status/:orderId ──

async function getRegistrationStatus(req, res) {
  try {
    console.log("/status route fired");
    const { orderId } = req.params;

    console.log(orderId);
    printOrderMap();

    if (orderIdExists(orderId)) {
      console.log("hello");
      const leaderRow = getOrderData(orderId);
      return res.json({
        status: 'registered',
        team: {
          id:        leaderRow.teamId,
          teamName:  leaderRow.teamName,
          status:    leaderRow.status,
          createdAt: leaderRow.createdAt,
        }
      });
    }

    // Check pending table
    const pending = await redis.get(`pending_registration:${orderId}`);
    if (pending) {
      console.log("not hello");
      return res.json({ status: 'pending', orderId });
    }
    console.log("not hello not found");
    res.status(404).json({ status: 'not_found', orderId });

  } catch (err) {
    console.error('[Hackathon] getRegistrationStatus error:', err);
    res.status(500).json({ error: err.message });
  }
}


// ─── POST /api/hackathon/promo ─────────────────
// Body: { promoCode: string }
// Response (valid):   { valid: true,  discount: number, finalAmountPaise: number, message: string }
// Response (invalid): { valid: false, message: string }

const PROMO_CODES = {
  'AURAXIS100': 10000,
  //'EARLY20':   20,
};

async function applyPromoCode(req, res) {
  try {
    const { promoCode } = req.body;

    if (!promoCode || typeof promoCode !== 'string') {
      return res.status(400).json({ valid: false, message: 'Promo code is required.' });
    }

    const code = promoCode.trim().toUpperCase();

    const baseAmountPaise = parseInt(process.env.REGISTRATION_FEE_PAISE, 10);
    const result = await resolvePromoCode(code, baseAmountPaise);

    if (!result.valid) {
      return res.status(200).json({ valid: false, message: result.message || 'Invalid promo code.' });
    }

    return res.status(200).json({
      valid:            true,
      discount:         result.discountPaise,
      finalAmountPaise: result.finalAmountPaise,
      message:          `Promo applied! ${(result.discountPaise / 100).toFixed(2)} Rs off — you pay ₹${(result.finalAmountPaise / 100).toFixed(2)}.`,
    });

  } catch (err) {
    console.error('[Hackathon] applyPromoCode error:', err);
    res.status(500).json({ valid: false, message: 'Something went wrong. Please try again.' });
  }
}


async function resolvePromoCode(code, baseAmountPaise) {
  const normalized    = code.trim().toUpperCase();
  const discountPaise = PROMO_CODES[normalized];
  if (discountPaise === undefined) {
    return { valid: false };
  }

  const currentUses = await redis.incr('promo_counter');
  const maxUses     = parseInt(process.env.MAX_PROMO_USES, 10);
  if (currentUses >= maxUses) {
    return { valid: false, message: 'Promo code usage limit has been reached.' };
  }

  if (discountPaise > baseAmountPaise) {
    return { valid: false, message: 'Promo Code not Applicable right now.' };
  }
  const finalAmountPaise = parseInt(baseAmountPaise - discountPaise, 10);
  return { valid: true, discountPaise, finalAmountPaise };
}


module.exports = {
  initiatePayment,
  handleWebhook,
  getRegistrationStatus,
  applyPromoCode,
};
